create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  customer_id integer not null references public.customers(id) on delete cascade,
  address_type text not null check (address_type in ('BILLING', 'SHIPPING')),
  label text null,
  address text not null,
  is_primary boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists customer_addresses_customer_id_idx
  on public.customer_addresses (customer_id);

create index if not exists customer_addresses_customer_type_idx
  on public.customer_addresses (customer_id, address_type);

create unique index if not exists customer_addresses_one_primary_per_type_idx
  on public.customer_addresses (customer_id, address_type)
  where is_primary = true;
