-- Separate persistence for grading step (no reworks).
CREATE TABLE IF NOT EXISTS public.process_grading_outputs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_step_run_id bigint NOT NULL,
  product_id integer NOT NULL,
  quantity_kg numeric NOT NULL,
  moisture_percent numeric,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT process_grading_outputs_process_step_run_id_fkey
    FOREIGN KEY (process_step_run_id) REFERENCES public.process_step_runs(id) ON DELETE CASCADE,
  CONSTRAINT process_grading_outputs_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.process_grading_waste (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sorting_run_id bigint NOT NULL,
  waste_type text NOT NULL,
  quantity_kg numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT process_grading_waste_sorting_run_id_fkey
    FOREIGN KEY (sorting_run_id) REFERENCES public.process_grading_outputs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS process_grading_outputs_process_step_run_id_idx
  ON public.process_grading_outputs(process_step_run_id);

CREATE INDEX IF NOT EXISTS process_grading_outputs_product_id_idx
  ON public.process_grading_outputs(product_id);

CREATE INDEX IF NOT EXISTS process_grading_waste_sorting_run_id_idx
  ON public.process_grading_waste(sorting_run_id);

DROP TRIGGER IF EXISTS process_grading_outputs_set_updated_at ON public.process_grading_outputs;
CREATE TRIGGER process_grading_outputs_set_updated_at
  BEFORE UPDATE ON public.process_grading_outputs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

GRANT ALL ON TABLE public.process_grading_outputs TO anon;
GRANT ALL ON TABLE public.process_grading_outputs TO authenticated;
GRANT ALL ON TABLE public.process_grading_outputs TO service_role;

GRANT ALL ON TABLE public.process_grading_waste TO anon;
GRANT ALL ON TABLE public.process_grading_waste TO authenticated;
GRANT ALL ON TABLE public.process_grading_waste TO service_role;

GRANT ALL ON SEQUENCE public.process_grading_outputs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.process_grading_outputs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.process_grading_outputs_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.process_grading_waste_id_seq TO anon;
GRANT ALL ON SEQUENCE public.process_grading_waste_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.process_grading_waste_id_seq TO service_role;
