BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.mixed_pack_batch_no_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE OR REPLACE FUNCTION public.generate_mixed_pack_batch_no()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_next bigint;
BEGIN
  v_next := nextval('public.mixed_pack_batch_no_seq');
  RETURN 'MP-' || lpad(v_next::text, 6, '0');
END;
$$;

CREATE TABLE IF NOT EXISTS public.mixed_pack_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_no text NOT NULL DEFAULT public.generate_mixed_pack_batch_no(),
  pack_name text NOT NULL,
  status text NOT NULL DEFAULT 'PACKAGED',
  inventory_type text NOT NULL DEFAULT 'mixed_pack',
  defined_pack_size numeric NULL,
  actual_total_qty numeric NOT NULL,
  warehouse_id integer NOT NULL REFERENCES public.warehouses(id),
  unit_id integer NULL REFERENCES public.units(id),
  require_exact_total boolean NOT NULL DEFAULT true,
  notes text NULL,
  created_by uuid NULL REFERENCES public.user_profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  supply_id bigint NULL REFERENCES public.supplies(id) ON DELETE SET NULL,
  supply_batch_id bigint NULL REFERENCES public.supply_batches(id) ON DELETE SET NULL,
  process_id bigint NULL REFERENCES public.processes(id) ON DELETE SET NULL,
  process_step_id bigint NULL REFERENCES public.process_steps(id) ON DELETE SET NULL,
  process_lot_run_id bigint NULL REFERENCES public.process_lot_runs(id) ON DELETE SET NULL,
  process_step_run_id bigint NULL REFERENCES public.process_step_runs(id) ON DELETE SET NULL,
  packaging_run_id bigint NULL REFERENCES public.process_packaging_runs(id) ON DELETE SET NULL,
  pack_entry_id bigint NULL REFERENCES public.process_packaging_pack_entries(id) ON DELETE SET NULL,
  storage_allocation_id bigint NULL REFERENCES public.process_packaging_storage_allocations(id) ON DELETE SET NULL,
  CONSTRAINT mixed_pack_batches_batch_no_key UNIQUE (batch_no),
  CONSTRAINT mixed_pack_batches_pack_name_check CHECK (length(trim(pack_name)) > 0),
  CONSTRAINT mixed_pack_batches_status_check CHECK (status = 'PACKAGED'),
  CONSTRAINT mixed_pack_batches_inventory_type_check CHECK (inventory_type = 'mixed_pack'),
  CONSTRAINT mixed_pack_batches_defined_pack_size_check CHECK (defined_pack_size IS NULL OR defined_pack_size > 0),
  CONSTRAINT mixed_pack_batches_actual_total_qty_check CHECK (actual_total_qty > 0)
);

CREATE TABLE IF NOT EXISTS public.mixed_pack_batch_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mixed_pack_batch_id bigint NOT NULL REFERENCES public.mixed_pack_batches(id) ON DELETE CASCADE,
  source_allocation_id bigint NOT NULL REFERENCES public.process_packaging_storage_allocations(id) ON DELETE RESTRICT,
  source_pack_entry_id bigint NULL REFERENCES public.process_packaging_pack_entries(id) ON DELETE RESTRICT,
  source_product_id integer NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  source_lot_run_id bigint NULL REFERENCES public.process_lot_runs(id) ON DELETE RESTRICT,
  quantity_used numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mixed_pack_batch_items_quantity_used_check CHECK (quantity_used > 0)
);

CREATE INDEX IF NOT EXISTS mixed_pack_batches_created_at_desc_idx
  ON public.mixed_pack_batches(created_at DESC);

CREATE INDEX IF NOT EXISTS mixed_pack_batch_items_batch_id_idx
  ON public.mixed_pack_batch_items(mixed_pack_batch_id);

CREATE INDEX IF NOT EXISTS mixed_pack_batch_items_source_allocation_id_idx
  ON public.mixed_pack_batch_items(source_allocation_id);

ALTER TABLE public.process_packaging_pack_entries
  ALTER COLUMN sorting_output_id DROP NOT NULL;

ALTER TABLE public.process_packaging_pack_entries
  ADD COLUMN IF NOT EXISTS mixed_pack_batch_id bigint NULL REFERENCES public.mixed_pack_batches(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS source_mode text NOT NULL DEFAULT 'SORTING_OUTPUT';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'process_packaging_pack_entries_source_mode_check'
  ) THEN
    ALTER TABLE public.process_packaging_pack_entries
      ADD CONSTRAINT process_packaging_pack_entries_source_mode_check
      CHECK (source_mode = ANY (ARRAY['SORTING_OUTPUT'::text, 'MIXED_PACK'::text]));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'process_packaging_pack_entries_source_reference_check'
  ) THEN
    ALTER TABLE public.process_packaging_pack_entries
      ADD CONSTRAINT process_packaging_pack_entries_source_reference_check
      CHECK (
        (source_mode = 'SORTING_OUTPUT' AND sorting_output_id IS NOT NULL AND mixed_pack_batch_id IS NULL)
        OR
        (source_mode = 'MIXED_PACK' AND sorting_output_id IS NULL AND mixed_pack_batch_id IS NOT NULL)
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS process_packaging_pack_entries_mixed_pack_batch_id_idx
  ON public.process_packaging_pack_entries(mixed_pack_batch_id);

CREATE OR REPLACE FUNCTION public.set_mixed_pack_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS mixed_pack_batches_set_updated_at ON public.mixed_pack_batches;
CREATE TRIGGER mixed_pack_batches_set_updated_at
  BEFORE UPDATE ON public.mixed_pack_batches
  FOR EACH ROW
  EXECUTE FUNCTION public.set_mixed_pack_updated_at();

DROP TRIGGER IF EXISTS mixed_pack_batch_items_set_updated_at ON public.mixed_pack_batch_items;
CREATE TRIGGER mixed_pack_batch_items_set_updated_at
  BEFORE UPDATE ON public.mixed_pack_batch_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_mixed_pack_updated_at();

CREATE OR REPLACE FUNCTION public.populate_and_guard_mixed_pack_batch_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_units_count integer;
  v_total_quantity numeric;
  v_quantity_per_unit numeric;
  v_shipped_units integer;
  v_other_consumed numeric;
  v_available numeric;
  v_pack_entry_id bigint;
  v_product_id integer;
  v_lot_run_id bigint;
  v_source_warehouse_id integer;
  v_batch_warehouse_id integer;
BEGIN
  IF NEW.source_allocation_id IS NULL THEN
    RAISE EXCEPTION 'source_allocation_id is required';
  END IF;

  IF NEW.quantity_used IS NULL OR NEW.quantity_used <= 0 THEN
    RAISE EXCEPTION 'quantity_used must be greater than zero';
  END IF;

  SELECT
    psa.units_count,
    psa.total_quantity_kg,
    psa.pack_entry_id,
    COALESCE(pe.product_id, so.product_id)::integer,
    plr.id,
    sup.warehouse_id
  INTO
    v_units_count,
    v_total_quantity,
    v_pack_entry_id,
    v_product_id,
    v_lot_run_id,
    v_source_warehouse_id
  FROM public.process_packaging_storage_allocations psa
  JOIN public.process_packaging_pack_entries pe
    ON pe.id = psa.pack_entry_id
  LEFT JOIN public.process_sorting_outputs so
    ON so.id = pe.sorting_output_id
  JOIN public.process_packaging_runs pr
    ON pr.id = psa.packaging_run_id
  JOIN public.process_step_runs psr
    ON psr.id = pr.process_step_run_id
  JOIN public.process_lot_runs plr
    ON plr.id = psr.process_lot_run_id
  JOIN public.supply_batches sb
    ON sb.id = plr.supply_batch_id
  JOIN public.supplies sup
    ON sup.id = sb.supply_id
  WHERE psa.id = NEW.source_allocation_id
  FOR UPDATE OF psa;

  IF v_units_count IS NULL THEN
    RAISE EXCEPTION 'Packaging allocation % not found', NEW.source_allocation_id;
  END IF;

  SELECT warehouse_id
  INTO v_batch_warehouse_id
  FROM public.mixed_pack_batches
  WHERE id = NEW.mixed_pack_batch_id;

  IF v_batch_warehouse_id IS NULL THEN
    RAISE EXCEPTION 'Mixed pack batch % not found', NEW.mixed_pack_batch_id;
  END IF;

  IF v_source_warehouse_id IS DISTINCT FROM v_batch_warehouse_id THEN
    RAISE EXCEPTION 'Source allocation % does not belong to warehouse %', NEW.source_allocation_id, v_batch_warehouse_id;
  END IF;

  v_quantity_per_unit :=
    CASE
      WHEN v_units_count > 0 THEN v_total_quantity / v_units_count::numeric
      ELSE 0
    END;

  SELECT COALESCE(SUM(spi.units_count), 0)::integer
  INTO v_shipped_units
  FROM public.shipment_pack_items spi
  JOIN public.shipments s
    ON s.id = spi.shipment_id
  WHERE spi.packaging_allocation_id = NEW.source_allocation_id
    AND s.doc_status <> 'CANCELLED';

  SELECT COALESCE(SUM(mbi.quantity_used), 0)
  INTO v_other_consumed
  FROM public.mixed_pack_batch_items mbi
  WHERE mbi.source_allocation_id = NEW.source_allocation_id
    AND (TG_OP <> 'UPDATE' OR mbi.id <> OLD.id);

  v_available := v_total_quantity - (COALESCE(v_shipped_units, 0) * v_quantity_per_unit) - COALESCE(v_other_consumed, 0);

  IF NEW.quantity_used > v_available + 0.000001 THEN
    RAISE EXCEPTION 'Requested quantity (%) exceeds allocation remaining quantity (%) for allocation %',
      NEW.quantity_used,
      GREATEST(v_available, 0),
      NEW.source_allocation_id;
  END IF;

  NEW.source_pack_entry_id := v_pack_entry_id;
  NEW.source_product_id := v_product_id;
  NEW.source_lot_run_id := v_lot_run_id;
  NEW.updated_at := now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS mixed_pack_batch_items_guard_trg ON public.mixed_pack_batch_items;
CREATE TRIGGER mixed_pack_batch_items_guard_trg
  BEFORE INSERT OR UPDATE ON public.mixed_pack_batch_items
  FOR EACH ROW
  EXECUTE FUNCTION public.populate_and_guard_mixed_pack_batch_item();

CREATE OR REPLACE VIEW public.mixed_pack_source_allocations AS
WITH shipped AS (
  SELECT
    spi.packaging_allocation_id,
    COALESCE(SUM(spi.units_count), 0)::integer AS shipped_units
  FROM public.shipment_pack_items spi
  JOIN public.shipments s
    ON s.id = spi.shipment_id
  WHERE s.doc_status <> 'CANCELLED'
  GROUP BY spi.packaging_allocation_id
),
mixed AS (
  SELECT
    mbi.source_allocation_id,
    COALESCE(SUM(mbi.quantity_used), 0) AS mixed_pack_consumed_qty
  FROM public.mixed_pack_batch_items mbi
  GROUP BY mbi.source_allocation_id
)
SELECT
  psa.id AS allocation_id,
  psa.packaging_run_id,
  psa.pack_entry_id,
  psa.storage_type,
  psa.units_count,
  psa.packs_per_unit,
  psa.total_packs,
  psa.total_quantity_kg,
  psa.created_at AS allocated_at,
  pe.pack_identifier,
  COALESCE(pe.product_id, so.product_id)::integer AS product_id,
  CASE
    WHEN pe.source_mode = 'MIXED_PACK' THEN mpb.pack_name
    ELSE prod.name
  END AS product_name,
  CASE
    WHEN pe.source_mode = 'MIXED_PACK' THEN NULL::text
    ELSE prod.sku
  END AS product_sku,
  prod.product_type,
  prod.base_unit_id AS unit_id,
  unit_ref.name AS unit_name,
  unit_ref.symbol AS unit_symbol,
  plr.id AS lot_run_id,
  plr.status AS lot_run_status,
  sb.id AS source_batch_id,
  sb.lot_no,
  sup.warehouse_id,
  wh.name AS warehouse_name,
  COALESCE(sh.shipped_units, 0)::integer AS shipped_units,
  COALESCE(mx.mixed_pack_consumed_qty, 0) AS mixed_pack_consumed_qty,
  CASE
    WHEN psa.units_count > 0 THEN psa.total_quantity_kg / psa.units_count::numeric
    ELSE 0
  END AS quantity_per_unit_kg,
  GREATEST(
    psa.total_quantity_kg
      - (COALESCE(sh.shipped_units, 0) * CASE WHEN psa.units_count > 0 THEN psa.total_quantity_kg / psa.units_count::numeric ELSE 0 END)
      - COALESCE(mx.mixed_pack_consumed_qty, 0),
    0
  ) AS remaining_quantity_kg,
  CASE
    WHEN psa.units_count > 0 AND psa.total_quantity_kg > 0
      THEN CEIL(COALESCE(mx.mixed_pack_consumed_qty, 0) / NULLIF(psa.total_quantity_kg / psa.units_count::numeric, 0))::integer
    ELSE 0
  END AS mixed_pack_reserved_units,
  GREATEST(
    psa.units_count
      - COALESCE(sh.shipped_units, 0)
      - CASE
          WHEN psa.units_count > 0 AND psa.total_quantity_kg > 0
            THEN CEIL(COALESCE(mx.mixed_pack_consumed_qty, 0) / NULLIF(psa.total_quantity_kg / psa.units_count::numeric, 0))::integer
          ELSE 0
        END,
    0
  ) AS remaining_units
FROM public.process_packaging_storage_allocations psa
JOIN public.process_packaging_pack_entries pe
  ON pe.id = psa.pack_entry_id
LEFT JOIN public.mixed_pack_batches mpb
  ON mpb.id = pe.mixed_pack_batch_id
LEFT JOIN public.process_sorting_outputs so
  ON so.id = pe.sorting_output_id
JOIN public.products prod
  ON prod.id = COALESCE(pe.product_id, so.product_id)::integer
LEFT JOIN public.units unit_ref
  ON unit_ref.id = prod.base_unit_id
JOIN public.process_packaging_runs pr
  ON pr.id = psa.packaging_run_id
JOIN public.process_step_runs psr
  ON psr.id = pr.process_step_run_id
JOIN public.process_lot_runs plr
  ON plr.id = psr.process_lot_run_id
JOIN public.supply_batches sb
  ON sb.id = plr.supply_batch_id
JOIN public.supplies sup
  ON sup.id = sb.supply_id
LEFT JOIN public.warehouses wh
  ON wh.id = sup.warehouse_id
LEFT JOIN shipped sh
  ON sh.packaging_allocation_id = psa.id
LEFT JOIN mixed mx
  ON mx.source_allocation_id = psa.id
WHERE plr.status = 'COMPLETED'
  AND prod.product_type = 'FINISHED';

CREATE OR REPLACE FUNCTION public.ensure_mixed_pack_bridge(
  p_batch_id bigint,
  p_warehouse_id integer,
  p_unit_id integer,
  p_pack_name text,
  p_total_qty numeric,
  p_notes text DEFAULT NULL
)
RETURNS TABLE(
  mixed_product_id integer,
  process_id bigint,
  process_step_id bigint,
  supply_id bigint,
  supply_batch_id bigint,
  process_lot_run_id bigint,
  process_step_run_id bigint,
  packaging_run_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_batch_no text;
  v_mixed_product_id integer;
  v_process_id bigint;
  v_process_step_id bigint;
  v_pack_step_name_id bigint;
  v_supply_id bigint;
  v_supply_batch_id bigint;
  v_process_lot_run_id bigint;
  v_process_step_run_id bigint;
  v_packaging_run_id bigint;
BEGIN
  SELECT batch_no
  INTO v_batch_no
  FROM public.mixed_pack_batches
  WHERE id = p_batch_id
  FOR UPDATE;

  IF v_batch_no IS NULL THEN
    RAISE EXCEPTION 'Mixed pack batch % not found', p_batch_id;
  END IF;

  SELECT id
  INTO v_mixed_product_id
  FROM public.products
  WHERE sku = 'MIXED-PACK'
  LIMIT 1;

  IF v_mixed_product_id IS NULL THEN
    INSERT INTO public.products (
      sku,
      name,
      status,
      notes,
      product_type,
      base_unit_id
    ) VALUES (
      'MIXED-PACK',
      'Mixed Pack',
      'ACTIVE',
      'System product used for mixed-pack packaging bridge rows.',
      'FINISHED',
      p_unit_id
    )
    RETURNING id INTO v_mixed_product_id;
  ELSIF p_unit_id IS NOT NULL THEN
    UPDATE public.products
    SET base_unit_id = COALESCE(base_unit_id, p_unit_id),
        updated_at = now()
    WHERE id = v_mixed_product_id;
  END IF;

  SELECT id
  INTO v_pack_step_name_id
  FROM public.process_step_names
  WHERE upper(code) = 'PACK'
  ORDER BY id
  LIMIT 1;

  IF v_pack_step_name_id IS NULL THEN
    RAISE EXCEPTION 'Packaging step name (PACK) not found';
  END IF;

  SELECT id
  INTO v_process_id
  FROM public.processes
  WHERE code = 'MIXED_PACK'
  LIMIT 1;

  IF v_process_id IS NULL THEN
    INSERT INTO public.processes (
      code,
      name,
      description,
      product_ids
    ) VALUES (
      'MIXED_PACK',
      'Mixed Pack Packaging',
      'Synthetic process used to bridge mixed-pack outputs into standard packaging tables.',
      ARRAY[v_mixed_product_id]
    )
    RETURNING id INTO v_process_id;
  END IF;

  SELECT id
  INTO v_process_step_id
  FROM public.process_steps
  WHERE process_id = v_process_id
    AND step_name_id = v_pack_step_name_id
  ORDER BY seq
  LIMIT 1;

  IF v_process_step_id IS NULL THEN
    INSERT INTO public.process_steps (
      process_id,
      seq,
      description,
      requires_qc,
      can_be_skipped,
      step_name_id
    ) VALUES (
      v_process_id,
      1,
      'Synthetic packaging step for mixed packs.',
      false,
      false,
      v_pack_step_name_id
    )
    RETURNING id INTO v_process_step_id;
  END IF;

  INSERT INTO public.supplies (
    warehouse_id,
    supplier_id,
    reference,
    received_at,
    received_by,
    doc_status,
    quality_status,
    notes,
    category_code
  ) VALUES (
    p_warehouse_id,
    NULL,
    'Mixed pack bridge',
    now(),
    auth.uid(),
    'ACCEPTED',
    'PASSED',
    COALESCE(NULLIF(trim(COALESCE(p_notes, '')), ''), format('Synthetic mixed-pack supply for %s', v_batch_no)),
    'PRODUCT'
  )
  RETURNING id INTO v_supply_id;

  INSERT INTO public.supply_batches (
    supply_id,
    product_id,
    unit_id,
    lot_no,
    received_qty,
    accepted_qty,
    current_qty,
    quality_status,
    process_status
  ) VALUES (
    v_supply_id,
    v_mixed_product_id,
    p_unit_id,
    v_batch_no,
    p_total_qty,
    p_total_qty,
    p_total_qty,
    'PASSED',
    'PROCESSED'
  )
  RETURNING id INTO v_supply_batch_id;

  INSERT INTO public.process_lot_runs (
    supply_batch_id,
    process_id,
    status,
    step_progress,
    started_at,
    completed_at
  ) VALUES (
    v_supply_batch_id,
    v_process_id,
    'COMPLETED',
    '[]'::jsonb,
    now(),
    now()
  )
  RETURNING id INTO v_process_lot_run_id;

  INSERT INTO public.process_step_runs (
    process_lot_run_id,
    process_step_id,
    status,
    started_at,
    completed_at,
    performed_by
  ) VALUES (
    v_process_lot_run_id,
    v_process_step_id,
    'COMPLETED',
    now(),
    now(),
    auth.uid()
  )
  RETURNING id INTO v_process_step_run_id;

  INSERT INTO public.process_packaging_runs (
    process_step_run_id,
    remarks
  ) VALUES (
    v_process_step_run_id,
    COALESCE(NULLIF(trim(COALESCE(p_notes, '')), ''), format('Synthetic packaging run for mixed pack %s', p_pack_name))
  )
  RETURNING id INTO v_packaging_run_id;

  RETURN QUERY
  SELECT
    v_mixed_product_id,
    v_process_id,
    v_process_step_id,
    v_supply_id,
    v_supply_batch_id,
    v_process_lot_run_id,
    v_process_step_run_id,
    v_packaging_run_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_mixed_pack(
  p_pack_name text,
  p_defined_pack_size numeric DEFAULT NULL,
  p_warehouse_id integer DEFAULT NULL,
  p_unit_id integer DEFAULT NULL,
  p_require_exact_total boolean DEFAULT true,
  p_lines jsonb DEFAULT '[]'::jsonb,
  p_packet_unit_code text DEFAULT NULL,
  p_pack_identifier text DEFAULT NULL,
  p_pack_size_kg numeric DEFAULT NULL,
  p_packing_type text DEFAULT NULL,
  p_storage_type text DEFAULT NULL,
  p_box_unit_code text DEFAULT NULL,
  p_units_count integer DEFAULT NULL,
  p_packs_per_unit integer DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS TABLE(mixed_pack_batch_id bigint, batch_no text, pack_entry_id bigint, storage_allocation_id bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_batch_id bigint;
  v_batch_no text;
  v_total_qty numeric;
  v_line_count integer;
  v_default_unit_id integer;
  v_source_warehouse_id integer;
  v_mismatch_count integer;
  v_bridge record;
  v_pack_entry_id bigint;
  v_storage_allocation_id bigint;
  v_total_packs integer;
BEGIN
  IF COALESCE(trim(p_pack_name), '') = '' THEN
    RAISE EXCEPTION 'Pack name is required';
  END IF;

  IF p_defined_pack_size IS NOT NULL AND p_defined_pack_size <= 0 THEN
    RAISE EXCEPTION 'Defined pack size must be greater than zero';
  END IF;

  IF p_pack_size_kg IS NULL OR p_pack_size_kg <= 0 THEN
    RAISE EXCEPTION 'Pack size is required and must be greater than zero';
  END IF;

  IF COALESCE(trim(p_packet_unit_code), '') = '' THEN
    RAISE EXCEPTION 'Packet unit code is required';
  END IF;

  IF COALESCE(trim(p_storage_type), '') = '' THEN
    RAISE EXCEPTION 'Storage type is required';
  END IF;

  IF p_units_count IS NULL OR p_units_count <= 0 THEN
    RAISE EXCEPTION 'Units count must be greater than zero';
  END IF;

  IF p_packs_per_unit IS NULL OR p_packs_per_unit <= 0 THEN
    RAISE EXCEPTION 'Packs per unit must be greater than zero';
  END IF;

  IF upper(p_storage_type) = 'BOX' AND COALESCE(trim(p_box_unit_code), '') = '' THEN
    RAISE EXCEPTION 'Box unit code is required for box allocations';
  END IF;

  IF jsonb_typeof(COALESCE(p_lines, '[]'::jsonb)) <> 'array' THEN
    RAISE EXCEPTION 'Lines payload must be an array';
  END IF;

  CREATE TEMP TABLE tmp_mixed_pack_lines (
    source_allocation_id bigint PRIMARY KEY,
    quantity_used numeric NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO tmp_mixed_pack_lines (source_allocation_id, quantity_used)
  SELECT
    (row->>'source_allocation_id')::bigint,
    SUM((row->>'quantity_used')::numeric)
  FROM jsonb_array_elements(COALESCE(p_lines, '[]'::jsonb)) AS row
  GROUP BY (row->>'source_allocation_id')::bigint;

  SELECT COUNT(*), COALESCE(SUM(quantity_used), 0)
  INTO v_line_count, v_total_qty
  FROM tmp_mixed_pack_lines;

  IF v_line_count = 0 THEN
    RAISE EXCEPTION 'At least one source line is required';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM tmp_mixed_pack_lines
    WHERE source_allocation_id IS NULL
      OR quantity_used IS NULL
      OR quantity_used <= 0
  ) THEN
    RAISE EXCEPTION 'Every source line must include a valid allocation and a quantity greater than zero';
  END IF;

  IF p_require_exact_total AND p_defined_pack_size IS NOT NULL AND abs(v_total_qty - p_defined_pack_size) > 0.000001 THEN
    RAISE EXCEPTION 'Selected total (%) does not match defined pack size (%)', v_total_qty, p_defined_pack_size;
  END IF;

  CREATE TEMP TABLE tmp_selected_allocations ON COMMIT DROP AS
  SELECT
    psa.id AS source_allocation_id,
    psa.pack_entry_id,
    psa.total_quantity_kg,
    psa.units_count,
    COALESCE(pe.product_id, so.product_id)::integer AS product_id,
    prod.base_unit_id,
    plr.id AS lot_run_id,
    sup.warehouse_id
  FROM public.process_packaging_storage_allocations psa
  JOIN tmp_mixed_pack_lines lines
    ON lines.source_allocation_id = psa.id
  JOIN public.process_packaging_pack_entries pe
    ON pe.id = psa.pack_entry_id
  LEFT JOIN public.process_sorting_outputs so
    ON so.id = pe.sorting_output_id
  JOIN public.products prod
    ON prod.id = COALESCE(pe.product_id, so.product_id)::integer
  JOIN public.process_packaging_runs pr
    ON pr.id = psa.packaging_run_id
  JOIN public.process_step_runs psr
    ON psr.id = pr.process_step_run_id
  JOIN public.process_lot_runs plr
    ON plr.id = psr.process_lot_run_id
  JOIN public.supply_batches sb
    ON sb.id = plr.supply_batch_id
  JOIN public.supplies sup
    ON sup.id = sb.supply_id
  WHERE plr.status = 'COMPLETED'
    AND prod.product_type = 'FINISHED'
  FOR UPDATE OF psa;

  IF (SELECT COUNT(*) FROM tmp_selected_allocations) <> v_line_count THEN
    RAISE EXCEPTION 'One or more selected source allocations are not eligible for mixed packs';
  END IF;

  SELECT MIN(warehouse_id), COUNT(DISTINCT warehouse_id)
  INTO v_source_warehouse_id, v_mismatch_count
  FROM tmp_selected_allocations;

  IF v_mismatch_count <> 1 THEN
    RAISE EXCEPTION 'All source allocations must belong to the same warehouse';
  END IF;

  IF p_warehouse_id IS NOT NULL AND p_warehouse_id <> v_source_warehouse_id THEN
    RAISE EXCEPTION 'Selected source allocations do not belong to warehouse %', p_warehouse_id;
  END IF;

  IF p_unit_id IS NULL THEN
    SELECT base_unit_id
    INTO v_default_unit_id
    FROM tmp_selected_allocations
    GROUP BY base_unit_id
    ORDER BY COUNT(*) DESC, base_unit_id NULLS LAST
    LIMIT 1;
  ELSE
    v_default_unit_id := p_unit_id;
  END IF;

  INSERT INTO public.mixed_pack_batches (
    pack_name,
    defined_pack_size,
    actual_total_qty,
    warehouse_id,
    unit_id,
    require_exact_total,
    notes,
    created_by
  ) VALUES (
    trim(p_pack_name),
    p_defined_pack_size,
    v_total_qty,
    COALESCE(p_warehouse_id, v_source_warehouse_id),
    v_default_unit_id,
    COALESCE(p_require_exact_total, true),
    NULLIF(trim(COALESCE(p_notes, '')), ''),
    auth.uid()
  )
  RETURNING id, mixed_pack_batches.batch_no
  INTO v_batch_id, v_batch_no;

  INSERT INTO public.mixed_pack_batch_items (
    mixed_pack_batch_id,
    source_allocation_id,
    quantity_used
  )
  SELECT
    v_batch_id,
    source_allocation_id,
    quantity_used
  FROM tmp_mixed_pack_lines
  ORDER BY source_allocation_id;

  SELECT *
  INTO v_bridge
  FROM public.ensure_mixed_pack_bridge(
    v_batch_id,
    COALESCE(p_warehouse_id, v_source_warehouse_id),
    v_default_unit_id,
    trim(p_pack_name),
    v_total_qty,
    p_notes
  );

  INSERT INTO public.process_packaging_pack_entries (
    packaging_run_id,
    sorting_output_id,
    mixed_pack_batch_id,
    source_mode,
    product_id,
    packet_unit_code,
    pack_identifier,
    quantity_kg,
    packing_type,
    pack_size_kg,
    damaged_pack_count,
    metal_check_status,
    metal_check_attempts
  ) VALUES (
    v_bridge.packaging_run_id,
    NULL,
    v_batch_id,
    'MIXED_PACK',
    v_bridge.mixed_product_id,
    trim(p_packet_unit_code),
    COALESCE(NULLIF(trim(COALESCE(p_pack_identifier, '')), ''), trim(p_packet_unit_code)),
    v_total_qty,
    NULLIF(trim(COALESCE(p_packing_type, '')), ''),
    p_pack_size_kg,
    0,
    NULL,
    0
  )
  RETURNING id, pack_count INTO v_pack_entry_id, v_total_packs;

  IF v_total_packs IS NULL OR v_total_packs <= 0 THEN
    RAISE EXCEPTION 'The selected quantity does not produce any full packs for pack size %', p_pack_size_kg;
  END IF;

  IF (p_units_count * p_packs_per_unit) > v_total_packs THEN
    RAISE EXCEPTION 'Requested allocation packs (%) exceed produced packs (%)', (p_units_count * p_packs_per_unit), v_total_packs;
  END IF;

  INSERT INTO public.process_packaging_storage_allocations (
    packaging_run_id,
    pack_entry_id,
    storage_type,
    box_unit_code,
    units_count,
    packs_per_unit,
    total_packs,
    total_quantity_kg,
    notes,
    created_by
  ) VALUES (
    v_bridge.packaging_run_id,
    v_pack_entry_id,
    upper(p_storage_type),
    CASE WHEN upper(p_storage_type) = 'BOX' THEN trim(p_box_unit_code) ELSE NULL END,
    p_units_count,
    p_packs_per_unit,
    p_units_count * p_packs_per_unit,
    (p_units_count * p_packs_per_unit) * p_pack_size_kg,
    NULLIF(trim(COALESCE(p_notes, '')), ''),
    auth.uid()
  )
  RETURNING id INTO v_storage_allocation_id;

  UPDATE public.mixed_pack_batches
  SET
    supply_id = v_bridge.supply_id,
    supply_batch_id = v_bridge.supply_batch_id,
    process_id = v_bridge.process_id,
    process_step_id = v_bridge.process_step_id,
    process_lot_run_id = v_bridge.process_lot_run_id,
    process_step_run_id = v_bridge.process_step_run_id,
    packaging_run_id = v_bridge.packaging_run_id,
    pack_entry_id = v_pack_entry_id,
    storage_allocation_id = v_storage_allocation_id,
    updated_at = now()
  WHERE id = v_batch_id;

  RETURN QUERY
  SELECT v_batch_id, v_batch_no, v_pack_entry_id, v_storage_allocation_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.guard_packaging_storage_allocation_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  shipped_units integer;
  mixed_reserved_units integer;
BEGIN
  SELECT COALESCE(SUM(spi.units_count), 0)::integer
  INTO shipped_units
  FROM public.shipment_pack_items spi
  JOIN public.shipments s
    ON s.id = spi.shipment_id
  WHERE spi.packaging_allocation_id = old.id
    AND s.doc_status <> 'CANCELLED';

  SELECT COALESCE(MAX(src.mixed_pack_reserved_units), 0)::integer
  INTO mixed_reserved_units
  FROM public.mixed_pack_source_allocations src
  WHERE src.allocation_id = old.id;

  IF tg_op = 'DELETE' THEN
    IF shipped_units > 0 OR mixed_reserved_units > 0 THEN
      RAISE EXCEPTION 'Cannot delete allocation %, shipped units %, mixed-pack reserved units %', old.id, shipped_units, mixed_reserved_units;
    END IF;
    RETURN old;
  END IF;

  IF tg_op = 'UPDATE' THEN
    IF new.units_count < (shipped_units + mixed_reserved_units) THEN
      RAISE EXCEPTION 'Cannot reduce units_count below used units (%). Allocation %', (shipped_units + mixed_reserved_units), old.id;
    END IF;
    RETURN new;
  END IF;

  RETURN COALESCE(new, old);
END;
$$;

CREATE OR REPLACE FUNCTION public.guard_shipment_pack_item_units()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  allocation_units integer;
  consumed_other integer;
  mixed_reserved_units integer;
  next_units integer;
BEGIN
  IF NEW.packaging_allocation_id IS NULL THEN
    RETURN NEW;
  END IF;

  next_units := COALESCE(NEW.units_count, 0);
  IF next_units <= 0 THEN
    RAISE EXCEPTION 'units_count must be > 0 when packaging_allocation_id is set';
  END IF;

  SELECT units_count
  INTO allocation_units
  FROM public.process_packaging_storage_allocations
  WHERE id = NEW.packaging_allocation_id
  FOR UPDATE;

  IF allocation_units IS NULL THEN
    RAISE EXCEPTION 'Packaging allocation % not found', NEW.packaging_allocation_id;
  END IF;

  SELECT COALESCE(SUM(spi.units_count), 0)::integer
  INTO consumed_other
  FROM public.shipment_pack_items spi
  JOIN public.shipments s
    ON s.id = spi.shipment_id
  WHERE spi.packaging_allocation_id = NEW.packaging_allocation_id
    AND s.doc_status <> 'CANCELLED'
    AND (tg_op <> 'UPDATE' OR spi.id <> OLD.id);

  SELECT COALESCE(MAX(src.mixed_pack_reserved_units), 0)::integer
  INTO mixed_reserved_units
  FROM public.mixed_pack_source_allocations src
  WHERE src.allocation_id = NEW.packaging_allocation_id;

  IF next_units > (allocation_units - consumed_other - mixed_reserved_units) THEN
    RAISE EXCEPTION 'Requested units (%) exceed allocation remaining units (%)',
      next_units,
      GREATEST(allocation_units - consumed_other - mixed_reserved_units, 0);
  END IF;

  RETURN NEW;
END;
$$;

ALTER TABLE public.mixed_pack_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mixed_pack_batch_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS authenticated_full_access ON public.mixed_pack_batches;
CREATE POLICY authenticated_full_access
  ON public.mixed_pack_batches
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS authenticated_full_access ON public.mixed_pack_batch_items;
CREATE POLICY authenticated_full_access
  ON public.mixed_pack_batch_items
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT ALL ON TABLE public.mixed_pack_batches TO authenticated, service_role;
GRANT ALL ON TABLE public.mixed_pack_batch_items TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.mixed_pack_batch_no_seq TO authenticated, service_role;
GRANT SELECT ON public.mixed_pack_source_allocations TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generate_mixed_pack_batch_no() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ensure_mixed_pack_bridge(bigint, integer, integer, text, numeric, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.create_mixed_pack(text, numeric, integer, integer, boolean, jsonb, text, text, numeric, text, text, text, integer, integer, text) TO authenticated, service_role;

COMMIT;
