create table if not exists public.supplier_contacts (
  id bigint generated by default as identity primary key,
  supplier_id integer not null references public.suppliers(id) on delete cascade,
  name text not null,
  email text null,
  phone text null,
  role text null,
  is_primary boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists supplier_contacts_supplier_id_idx
  on public.supplier_contacts (supplier_id);

create unique index if not exists supplier_contacts_one_primary_per_supplier_idx
  on public.supplier_contacts (supplier_id)
  where is_primary = true;
