import type { InspectionSectionDefinition } from '@/types/inspection'

const glassInspectionRegister = {
  title: 'Glass and Brittle Plastic Register - Weekly',
  checkedByLabel: 'Checked by',
  dateLabel: 'Date',
  riskLegend: [
    '1. Slight risk - no action required',
    '2. Medium risk - action when opportunity occurs',
    '3. Urgent action or removal of object',
  ],
  riskOptions: ['1', '2', '3'],
  entriesTitle: 'Glass Inspection Entries',
  entriesDescription: 'Review existing inspection records before starting a new weekly register.',
  entriesStartLabel: 'Start Inspection',
  entriesHeaders: ['Date', 'Checked by', 'Areas checked', 'Status', 'Action'],
  registerGroups: [
    {
      area: 'Production Area 1',
      rows: [
        { item: 'Lights', totalQty: '14' },
        { item: 'EFC', totalQty: '3' },
        { item: 'Cameras', totalQty: '5' },
        { item: 'Wall clocks', totalQty: '1' },
        { item: 'Moth traps', totalQty: '4' },
        { item: 'Oven buttons', totalQty: '6' },
        { item: 'Oven Door', totalQty: '1' },
        { item: 'Vacuum Seal door', totalQty: '1' },
        { item: 'Vacuum Seal display', totalQty: '1' },
        { item: 'Vacuum Seal Emergency button', totalQty: '1' },
        { item: 'Vacuum Seal Gauge', totalQty: '1' },
        { item: 'Geyser', totalQty: '1' },
        { item: 'Dispensers', totalQty: '2' },
        { item: 'Windows (at the back)', totalQty: '6' },
        { item: 'Floor Scales display', totalQty: '2' },
        { item: 'Black crates (M)', totalQty: '25' },
        { item: 'Black crates (S)', totalQty: '25' },
        { item: 'Red crates', totalQty: '9' },
        { item: 'Blue crates', totalQty: '250' },
        { item: 'Orange crates', totalQty: '250' },
        { item: 'Plastic ruler', totalQty: '1' },
        { item: 'Measuring cups', totalQty: '3' },
        { item: 'Bowls', totalQty: '7' },
        { item: 'Grading Machine Bowls', totalQty: '6' },
        { item: 'Blender Display', totalQty: '1' },
        { item: 'Blender Buttons', totalQty: '6' },
        { item: 'Nitrogen Gas Cylinder Gauges', totalQty: '2' },
        { item: 'Waste Bin', totalQty: '1' },
        { item: 'Nitrogen Gas Cylinder Gauges', totalQty: '2' },
        { item: 'Metal Detector Display', totalQty: '1' },
        { item: 'Metal Detector Emergency light', totalQty: '1' },
        { item: 'Beta Pack Glass Doors', totalQty: '2' },
        { item: 'Beta Pack Display', totalQty: '4' },
        { item: 'Beta Pack Buttons', totalQty: '5' },
        { item: 'Beta Pack White conv Belt', totalQty: '1' },
        { item: 'Compressor Display', totalQty: '1' },
      ],
    },
    {
      area: 'Dryer',
      rows: [
        { item: 'C/ Light Box', totalQty: '2' },
        { item: 'Light', totalQty: '1' },
        { item: 'Air Dryer Gauge', totalQty: '1' },
        { item: 'Air Dryer Switch', totalQty: '1' },
        { item: 'Dryer Electric Box', totalQty: '1' },
        { item: 'Dryer Electric Box Switches/ Buttons', totalQty: '9' },
      ],
    },
    {
      area: 'Office',
      rows: [
        { item: 'Lights', totalQty: '2' },
        { item: 'Hand Wash Basin', totalQty: '1' },
        { item: 'Moisture Analyzer', totalQty: '1' },
        { item: 'Dry Bath', totalQty: '1' },
        { item: 'Glass door', totalQty: '2' },
        { item: 'Computers', totalQty: '2' },
        { item: 'Printers', totalQty: '2' },
        { item: 'Emergency lights', totalQty: '6' },
        { item: 'Dispensers', totalQty: '2' },
        { item: 'Ipad', totalQty: '1' },
        { item: 'Mr Delivery device', totalQty: '1' },
        { item: 'Certificate Frames', totalQty: '3' },
        { item: 'Router', totalQty: '1' },
        { item: 'Emergency horn', totalQty: '1' },
        { item: 'Emergency container', totalQty: '1' },
      ],
    },
    {
      area: 'Storage Area 1',
      rows: [
        { item: 'Aircon', totalQty: '1' },
        { item: 'Lights', totalQty: '3' },
        { item: 'C/ Light Box', totalQty: '1' },
        { item: 'H/ Machine hard plastic', totalQty: '7' },
      ],
    },
    {
      area: 'Storage Area 2',
      rows: [
        { item: 'Lights', totalQty: '3' },
        { item: 'Dispensers', totalQty: '2' },
        { item: 'EFC', totalQty: '1' },
        { item: 'Moth Trap', totalQty: '1' },
      ],
    },
    {
      area: 'Storage Area 3',
      rows: [{ item: 'Aircon', totalQty: '1' }],
    },
    {
      area: 'Change room',
      rows: [
        { item: 'Control Box', totalQty: '2' },
        { item: 'Light', totalQty: '1' },
      ],
    },
    {
      area: 'Ablution / Toilet',
      rows: [
        { item: 'Dispenser', totalQty: '2' },
        { item: 'Window', totalQty: '1' },
        { item: 'Mirror', totalQty: '1' },
      ],
    },
    {
      area: 'Canteen',
      rows: [
        { item: 'Windows', totalQty: '5' },
        { item: 'Light bulbs', totalQty: '1' },
        { item: 'Microwave', totalQty: '1' },
        { item: 'Glass door panels', totalQty: '11' },
        { item: 'Hand Wash', totalQty: '1' },
      ],
    },
  ],
  signoffLabel: 'Management / Supervisor Signature',
} as const

const maintenanceJobCardTemplate = {
  headerFields: [
    'Site Contact',
    'Name Of Contractor / Company name',
    'Date',
    'Contact No',
    'Contact number',
    'Area',
    'Order number',
    'Number of workers',
    'Job Card No',
  ],
  serviceTypes: ['Employer', 'Repairs', 'Contractor'],
  beforeProceedingTitle: 'Before Proceeding into production area',
  beforeProceedingChecks: [
    { label: 'Tools and consumables inventory completed?' },
    { label: 'Tools & consumable sanitized?' },
    { label: 'Safety Clothing provided?' },
    { label: 'Employer / Visitors Medical Questionnaires completed?' },
  ],
  completionTitle: 'Upon Completion of Work',
  completionChecks: [
    { label: 'Inventory of Tools & consumables checked?' },
    { label: 'Has the area of repair been checked by the site contact?' },
    { label: 'Has the sanitation team been dispatched to clean the area?' },
  ],
  inventoryTitle: 'Inventory',
  toolsHeaders: ['Tools (Describe)', 'Quantity In', 'Quantity Out', 'Signed', 'NCR – No.'],
  toolRows: 4,
  materialsHeaders: ['Materials ( Nails, Cable ties, lubrications)', 'Quantity In', 'Quantity Used', 'Quantity Out', 'Signed', 'NCR – No.'],
  materialRows: 4,
  detailLabel: 'Detail of maintenance',
  signoffs: [
    'Contractor Sign (sign)',
    'Maintenance Staff and QC (Sign)',
    'Production Manager / Maintenance Manager (sign)',
  ],
} as const

const chemicalVerificationTemplate = {
  headers: [
    'Date',
    'Chemical Name',
    'Batch Details',
    'Quantity Issued',
    'Dilution Concentration Verified & By',
    'Issued To',
    'Issued By',
  ],
  rowCount: 14,
  notes: [
    'Special cleaning chemical concentration to be verified weekly.',
    'Oxiacid dilution concentration to be verified with every issue / use.',
  ],
  signoffLabel: 'Management / Supervisor Signature',
} as const

const cleaningCorrectiveActionHeaders = [
  'Date',
  'Non-conformance Reported',
  'Corrective action made',
  'Sign off',
] as const

const cleaningVerificationTemplates = {
  daily: {
    frequencyLabel: 'Daily Checks',
    sections: [
      {
        area: 'Production Area, Storage Areas, Dispatch & Receiving',
        colorCode: 'Yellow / Blue / Grey / Pink',
        items: [
          'Floors',
          'Tables',
          'Basins / Taps',
          'Sealer',
          'Scales',
          'Dust Bin',
          'Utensils',
          'Hand wash Basin / Taps',
          'Product washing Basin / Taps',
          'Drains',
          'Cleaning Equipment',
        ],
      },
      {
        area: 'Staff Toilets & Management Toilets',
        colorCode: 'Red',
        items: [
          'Floors / Tiles',
          'Cleaning Equipment',
          'H/Towel Dispenser',
          'Soap / Sanitiser Dispenser',
          'Basin / Taps',
          'Waste Bins',
          'Door Handles',
        ],
      },
      {
        area: 'Canteen / Equipment Storage',
        colorCode: 'Green',
        items: [
          'Floors',
          'Waste Bins',
          'Food Lockers',
          'Microwave',
          'Kettle',
          'Sanitiser Dispenser',
          'Tables',
          'Chairs',
        ],
      },
      {
        area: 'Change Room',
        colorCode: 'Red',
        items: ['Floors', 'Drains', 'Sanitiser Dispenser', 'Door Handle'],
      },
      {
        area: 'Office / Shop',
        colorCode: 'White',
        items: [
          'Floors',
          'Dustbins',
          'Net / Beard Dispenser',
          'Sanitiser Dispenser',
          'Tables',
          'Printers & PCs',
          'Chairs',
        ],
      },
      {
        area: 'Outside / Yard',
        colorCode: 'Black',
        items: ['Floors - Sweeping', 'Dustbins', 'Drains'],
      },
    ],
    correctiveActionHeaders: cleaningCorrectiveActionHeaders,
    correctiveActionRows: 6,
    signoffLabel: 'Prod Manager / Prod Admin Signature',
  },
  weekly: {
    frequencyLabel: 'Weekly Checks',
    sections: [
      {
        area: 'Production Area, Storage Areas, Dispatch & Receiving',
        colorCode: 'Yellow / Blue / Grey / Pink',
        items: [
          'Floors',
          'Door Frames',
          'Cleaning Equipments',
          'P/Towel Dispenser',
          'Scales',
          'Compressor',
          'Grading Machine 1',
          'Grading Machine 2',
          'Sealer',
          'Vacuum Packer 1',
          'Vacuum Packer 2',
          'Vacuum Packer 3',
          'Drier',
          'Sanitiser Dispenser',
          'Soap Dispenser',
          'Toolbox',
          'Gas Cylinders',
        ],
      },
      {
        area: 'Canteen / Equipment Storage',
        colorCode: 'Green',
        items: ['Door / Glass panel', 'Tables / Legs', 'Plugs'],
      },
      {
        area: 'Change Room',
        colorCode: 'Red',
        items: [
          'Floors',
          'Uniform',
          'Sanitiser Dispenser',
          'Door / Frames',
          'Lockers / Cages',
          'Uniform Rack',
        ],
      },
      {
        area: 'Office / Shop',
        colorCode: 'White',
        items: [
          'Tables',
          'Display Shelves',
          'Uniform Rack',
          'Hand washing station',
          'Cupboards',
        ],
      },
    ],
    correctiveActionHeaders: cleaningCorrectiveActionHeaders,
    correctiveActionRows: 6,
    signoffLabel: 'Prod Manager / Prod Admin Signature',
  },
  monthly: {
    frequencyLabel: 'Monthly Checks',
    sections: [
      {
        area: 'Production Area, Storage Areas, Dispatch & Receiving',
        colorCode: 'Yellow / Blue / Grey / Pink',
        items: [
          'Door / Frames',
          'Walls & plugs',
          'Trolleys',
          'Tables',
          'Old Packing Machine',
          'Old oil machines',
          'Oven',
          'Utensils',
          'Electric Fly Unit',
          'Compressor',
          'Gas Cage',
          'Plugs',
          'Fans',
          'Pallet Rack',
          'Trolleys',
          'Fire Equipment',
        ],
      },
      {
        area: 'Staff Toilets & Management Toilets',
        colorCode: 'Red',
        items: ['Walls / Tiles', 'Window Fly Screen'],
      },
      {
        area: 'Canteen / Equipment Storage',
        colorCode: 'Green',
        items: [
          'Walls',
          'Chairs',
          'Stove',
          'Pots',
          'Door / Glass panel',
          'Generator',
          'Compressor',
        ],
      },
      {
        area: 'Change Room',
        colorCode: 'Red',
        items: ['Lockers / Cages', 'Basin / Taps', 'Drains'],
      },
      {
        area: 'Office / Shop',
        colorCode: 'White',
        items: ['File Shelves', 'Chemical Cabinet', 'Plugs', 'Doors / Frames'],
      },
    ],
    correctiveActionHeaders: cleaningCorrectiveActionHeaders,
    correctiveActionRows: 6,
    signoffLabel: 'Prod Manager / Prod Admin Signature',
  },
  annual: {
    frequencyLabel: 'Annual Checks',
    sections: [
      {
        area: 'Production Area, Storage Areas, Dispatch & Receiving',
        colorCode: 'Yellow / Blue / Grey / Pink',
        items: ['Windows', 'Walls', 'Lights'],
      },
      {
        area: 'Staff Toilets & Management Toilets',
        colorCode: 'Red',
        items: ['Lights'],
      },
      {
        area: 'Office / Shop',
        colorCode: 'White',
        items: ['Lights'],
      },
    ],
    correctiveActionHeaders: cleaningCorrectiveActionHeaders,
    correctiveActionRows: 6,
    signoffLabel: 'Prod Manager / Prod Admin Signature',
  },
} as const

const ablutionFacilityTemplate = {
  title: 'Ablution Facility Record',
  frequencyLabel: 'Daily',
  dateLabel: 'Date',
  checkpoints: [
    'Soap dispensers have enough soap.',
    'Disposable Paper Towels are in place.',
    'Paper Towel waste bin is emptied.',
    'Toilets are in working order.',
    'Toilets and basins are clean.',
    'No leaking taps.',
    'Toilet paper is available.',
    'Ablution windows are open for fresh air.',
    'Ablution floors are clean.',
    'No blocked drains.',
    'Ablution Brushware is in place.',
  ],
  lockerChecks: [
    'No protective clothing in the lockers',
    'No food stored in the lockers',
    'Lockers are clean and pest free',
  ],
  signoffLabel: 'Signed Off',
  legend: 'C = (√) Conformance / NC = (X) Non-conformance',
  correctiveActionLabel: 'Corrective Actions',
} as const

const hygieneRecordTemplate = {
  title: 'Daily Hygiene Record',
  checkedByLabel: 'Check Done by',
  namesCheckedLabel: 'Names of personal checked / sampled',
  requirementsIntro:
    'Requirements that failed the inspection will be corrected before it is signed off.',
  commentsLabel: 'Comments',
  requirements: [
    'No strongly scented perfumes',
    'No open wounds and skin infections',
    'No flu symptoms and runny tummy',
    'No bad body odours',
    'Hair net on & cover 100% of hair',
    'Clean uniform on',
    'Clean safety boots',
    'No eating or drinking of any sort',
    'Hand wash soap & sanitizer',
    'Locker inspection (no food present) - weekly',
    'No nail polish. False nails are not allowed inside factory',
  ],
} as const

const visitorQuestionnaireTemplate = {
  title: 'Visitors Questionnaire',
  headerFields: [
    'Date',
    'Person responsible for completion of this document',
    'Visitors / Contractor / Name',
    'Company',
    'Reason for visit',
    'Contact Number',
  ],
  declarationLabel: 'Anything to declare',
  healthQuestionHeaders: ['Have you suffered from', 'Yes', 'No', 'Details, when?'],
  healthQuestions: [
    'Typhoid (fever caused by Salmonella bacteria also known as enteric fever)',
    'Dysentery (severe diarrhoea)',
    'Salmonellosis',
    'Cough with phlegm (mucus) or bronchitis',
    'Discharging ears or eyes',
    'Eye infection',
    'Recurrent cold sores',
    'Frequent sore throat',
    'Persistent cold or flu',
    'Skin infections or boils',
    'Tuberculosis',
    'Tapeworm infestation',
    'Any other sickness to declare',
    'Have you visited a food plant in the last 24 hours? If yes, indicate type.',
  ],
  recentConditionHeaders: ['In the last 7 days have you suffered from', 'Yes', 'No', 'Details'],
  recentConditionQuestions: ['Diarrhoea, nausea or vomiting', 'Jaundice (Hepatitis)'],
  travelQuestions: [
    'Have you travelled out of the country recently?',
    'If YES, did you suffer from any illness, or were you in contact with any person suffering from Typhoid, Cholera or Enteric Fever whilst you were there?',
    'Have you suffered from any illness since your return?',
    'If YES, have you received medical attention and been subsequently "signed off" by a GP?',
    'Do you have any cuts on your forearms?',
    'Do you wear contact lenses or spectacles?',
  ],
  notice:
    'If you have answered YES to any of the above questions, there may be restrictions imposed upon your movement into the processing facility.',
  inductionTrainingItems: [
    'Hair restraints (mop caps) must be worn and all hair and ears must be covered completely.',
    'Visitor coats are mandatory.',
    'No jewellery is to be worn.',
    'Personal property such as handbags, mobile phones and smoking utensils are prohibited.',
    'Eating and drinking is prohibited, including chewing gum.',
    'Smoking is prohibited in all areas except in designated smoking areas.',
    'Follow hygiene oriented behavior, such as do not touch or have direct contact with food items, cover your mouth and nose when sneezing or coughing, and prevent possible contamination of food items.',
    'If you have manicure and or nail polish, gloves will be issued to cover the manicure or nail polish.',
  ],
  declarationText:
    'I undertake to follow the health and safety instructions outlined to me by my site contact. I confirm that the answers that I have given have been accurate. I understand that this is a food preparation facility and that I must avoid any action that might cause contamination of the product.',
  signoffFields: ['Visitor Signature', 'Employee Signature', 'Site contact name'],
  authorizationLabel: 'Authorized to proceed into facility',
  additionalObservations: [
    'Contact lens wearers must inform the site contact if a lens is lost whilst on the premises.',
    'Spectacle wearers must inform the site contact if a lens or metal part becomes dislodged or lost.',
  ],
} as const

export const inspectionSections: InspectionSectionDefinition[] = [
  {
    key: 'glass-inspection',
    label: 'Glass Inspection',
    shortLabel: 'Glass',
    icon: 'glass',
    group: 'Weekly Inspections',
    frequency: 'WEEKLY',
    description: 'Verify that glass registers, breakage controls, and shielded fittings remain compliant across production and storage zones.',
    summary: 'Weekly verification of glass-control points, intact covers, and escalation readiness.',
    statusLabel: 'Due this week',
    statusTone: 'olive',
    completionExpectation: 'One signed inspection per production week.',
    evidenceLabel: 'Attach breakage log references and area photos when exceptions are found.',
    glassTemplate: glassInspectionRegister,
    checklist: [
      { id: 'glass-register', label: 'Glass register reviewed', note: 'Confirm each listed item still matches the physical location and condition.' },
      { id: 'glass-condition', label: 'Glass and covers intact', note: 'Check lights, gauges, windows, and sight glasses for chips or cracks.' },
      { id: 'glass-response', label: 'Breakage response materials available', note: 'Verify cleanup kit, incident tags, and isolation guidance are present.' },
    ],
    fields: [
      { id: 'area-owner', label: 'Area owner', helper: 'Responsible supervisor for the weekly review.', type: 'person', placeholder: 'Select supervisor' },
      { id: 'week-ending', label: 'Week ending', helper: 'Inspection period end date.', type: 'date', placeholder: 'Select date' },
      { id: 'deviation-summary', label: 'Deviation summary', helper: 'Record any damaged items or follow-up actions.', type: 'textarea', placeholder: 'Document findings and corrective actions' },
    ],
  },
  {
    key: 'prp-inspection',
    label: 'PRP Inspection',
    shortLabel: 'PRP',
    icon: 'shield',
    group: 'Monthly Inspections',
    frequency: 'MONTHLY',
    description: 'Review prerequisite programme controls across personnel practices, premises, equipment condition, and sanitation readiness.',
    summary: 'Monthly PRP walk-through combining hygiene, facilities, pest, and housekeeping controls.',
    statusLabel: 'Planned this month',
    statusTone: 'sky',
    completionExpectation: 'One consolidated programme inspection each month.',
    evidenceLabel: 'Link corrective action tickets and CAPA references where controls fail.',
    checklist: [
      { id: 'prp-facility', label: 'Facility and process flow reviewed', note: 'Inspect segregation, zoning, and material-handling readiness.' },
      { id: 'prp-hygiene', label: 'Personnel and hygiene controls reviewed', note: 'Confirm PPE, handwash, and entry practices align to standard.' },
      { id: 'prp-cleaning', label: 'Cleaning and housekeeping controls reviewed', note: 'Review sanitation execution, verification, and escalation.' },
      { id: 'prp-pest', label: 'Pest and external-risk controls reviewed', note: 'Check bait maps, external doors, and evidence of pest activity.' },
    ],
    fields: [
      { id: 'inspection-month', label: 'Inspection month', helper: 'Reporting month for the PRP review.', type: 'date', placeholder: 'Select month' },
      { id: 'lead-inspector', label: 'Lead inspector', helper: 'Primary owner of the review.', type: 'person', placeholder: 'Select lead' },
      { id: 'overall-rating', label: 'Overall rating', helper: 'UI-only placeholder for future scoring.', type: 'select', placeholder: 'Select rating' },
    ],
  },
  {
    key: 'job-card',
    label: 'Job Card',
    shortLabel: 'Job Card',
    icon: 'file-text',
    group: 'When Required Records',
    frequency: 'WHEN_REQUIRED',
    description: 'Issue an ad hoc maintenance or corrective-action job card when site conditions, equipment faults, or support actions need formal tracking.',
    summary: 'On-demand operational job card authoring with asset, issue, and approval placeholders.',
    statusLabel: 'Created when needed',
    statusTone: 'amber',
    completionExpectation: 'Open only when a maintenance or corrective task must be formally logged.',
    evidenceLabel: 'Capture related work orders, contractor notes, or completion images when available.',
    jobCardTemplate: maintenanceJobCardTemplate,
    checklist: [
      { id: 'job-card-scope', label: 'Scope clearly defined', note: 'Describe the defect, location, and expected outcome.' },
      { id: 'job-card-priority', label: 'Priority and impact classified', note: 'Mark food-safety, downtime, or compliance implications.' },
    ],
    fields: [
      { id: 'asset-reference', label: 'Asset or location', helper: 'Equipment tag, line, or room reference.', type: 'text', placeholder: 'Enter asset or location' },
      { id: 'requested-by', label: 'Requested by', helper: 'Originator of the job card.', type: 'person', placeholder: 'Select requester' },
      { id: 'job-details', label: 'Job details', helper: 'Detailed description of work required.', type: 'textarea', placeholder: 'Describe the work request' },
      { id: 'target-date', label: 'Target date', helper: 'Requested completion date.', type: 'date', placeholder: 'Select date' },
    ],
  },
  {
    key: 'chemical-issue-dilution-verification',
    label: 'Chemical Issue Dilution Verification',
    shortLabel: 'Chemical',
    icon: 'flask',
    group: 'When Required Records',
    frequency: 'WHEN_REQUIRED',
    description: 'Record ad hoc verification that issued chemicals were diluted to the approved concentration before use.',
    summary: 'On-demand verification of chemical issue, concentration, operator, and approval details.',
    statusLabel: 'Triggered by issue',
    statusTone: 'amber',
    completionExpectation: 'Create a record whenever chemical issue and dilution need verification.',
    evidenceLabel: 'Placeholder for concentration photos, issue tickets, and calibration references.',
    chemicalVerificationTemplate,
    checklist: [
      { id: 'chemical-label', label: 'Chemical and label verified', note: 'Confirm the correct product and approved instruction are being used.' },
      { id: 'chemical-concentration', label: 'Dilution concentration verified', note: 'Check target ratio against the issue instruction or SOP.' },
      { id: 'chemical-equipment', label: 'Dispensing equipment suitable', note: 'Confirm container, dosing tool, and measuring device are fit for use.' },
    ],
    fields: [
      { id: 'chemical-name', label: 'Chemical issued', helper: 'Name of the issued chemical.', type: 'text', placeholder: 'Enter chemical name' },
      { id: 'prepared-by', label: 'Prepared by', helper: 'Operator preparing the dilution.', type: 'person', placeholder: 'Select operator' },
      { id: 'ratio', label: 'Dilution ratio', helper: 'Approved ratio or concentration.', type: 'text', placeholder: 'e.g. 1:100 or 200 ppm' },
      { id: 'verification-notes', label: 'Verification notes', helper: 'Document any corrective action or observation.', type: 'textarea', placeholder: 'Add verification notes' },
    ],
  },
  {
    key: 'cleaning-verification-daily',
    label: 'Cleaning Verification - Daily',
    shortLabel: 'Cleaning Daily',
    icon: 'sparkles',
    group: 'Cleaning Verification',
    frequency: 'DAILY',
    description: 'Check daily cleaning execution, line readiness, and immediate pre-operational hygiene conditions.',
    summary: 'Daily cleaning verification focused on execution quality and readiness to run.',
    statusLabel: 'Due today',
    statusTone: 'olive',
    completionExpectation: 'One verification per operating day.',
    evidenceLabel: 'Capture swab references, corrective actions, and signoff notes where needed.',
    cleaningVerificationTemplate: cleaningVerificationTemplates.daily,
    checklist: [
      { id: 'clean-daily-surfaces', label: 'Food-contact surfaces acceptable', note: 'Inspect visual cleanliness and residue control.' },
      { id: 'clean-daily-tools', label: 'Cleaning tools identified and stored correctly', note: 'Check segregation and storage condition of brushes, buckets, and chemicals.' },
      { id: 'clean-daily-release', label: 'Area released for operation', note: 'Confirm production can start without hygiene-related hold points.' },
    ],
    fields: [
      { id: 'verified-by', label: 'Verified by', helper: 'Responsible verifier for the daily release.', type: 'person', placeholder: 'Select verifier' },
      { id: 'shift', label: 'Shift', helper: 'Shift or crew for the verification.', type: 'select', placeholder: 'Select shift' },
      { id: 'notes', label: 'Notes', helper: 'Document deviations or hold points.', type: 'textarea', placeholder: 'Add daily verification notes' },
    ],
  },
  {
    key: 'cleaning-verification-weekly',
    label: 'Cleaning Verification - Weekly',
    shortLabel: 'Cleaning Weekly',
    icon: 'calendar-check',
    group: 'Cleaning Verification',
    frequency: 'WEEKLY',
    description: 'Review weekly cleaning depth, schedule adherence, and area-level hygiene consistency.',
    summary: 'Weekly verification of deep-clean execution and trend-level hygiene performance.',
    statusLabel: 'Due this week',
    statusTone: 'olive',
    completionExpectation: 'One weekly deep-clean verification.',
    evidenceLabel: 'Link deviations to weekly sanitation follow-ups and trend observations.',
    cleaningVerificationTemplate: cleaningVerificationTemplates.weekly,
    checklist: [
      { id: 'clean-weekly-plan', label: 'Weekly cleaning plan completed', note: 'Confirm all planned deep-clean tasks were executed.' },
      { id: 'clean-weekly-high-risk', label: 'High-risk areas inspected', note: 'Inspect drains, overheads, and difficult-access areas.' },
      { id: 'clean-weekly-trends', label: 'Recurring issues reviewed', note: 'Review repeated hygiene failures or incomplete tasks.' },
    ],
    fields: [
      { id: 'week-owner', label: 'Week owner', helper: 'Lead responsible for the weekly programme.', type: 'person', placeholder: 'Select owner' },
      { id: 'week-ending', label: 'Week ending', helper: 'End of the weekly review period.', type: 'date', placeholder: 'Select date' },
      { id: 'weekly-comments', label: 'Comments', helper: 'Trend notes or pending actions.', type: 'textarea', placeholder: 'Add weekly review comments' },
    ],
  },
  {
    key: 'cleaning-verification-monthly',
    label: 'Cleaning Verification - Monthly',
    shortLabel: 'Cleaning Monthly',
    icon: 'calendar-range',
    group: 'Cleaning Verification',
    frequency: 'MONTHLY',
    description: 'Assess monthly sanitation programme effectiveness, verification trends, and unresolved cleaning risks.',
    summary: 'Monthly review of sanitation performance, escalations, and programme effectiveness.',
    statusLabel: 'Planned this month',
    statusTone: 'sky',
    completionExpectation: 'One sanitation programme review per month.',
    evidenceLabel: 'Future placeholder for monthly trend packs, verification scores, and escalation evidence.',
    cleaningVerificationTemplate: cleaningVerificationTemplates.monthly,
    checklist: [
      { id: 'clean-monthly-trending', label: 'Monthly verification trends reviewed', note: 'Review recurring misses, swab failures, and persistent hotspots.' },
      { id: 'clean-monthly-resources', label: 'Resources and tools reviewed', note: 'Check adequacy of chemicals, tools, and manpower allocation.' },
      { id: 'clean-monthly-actions', label: 'Outstanding actions tracked', note: 'Confirm unresolved issues are assigned and dated.' },
    ],
    fields: [
      { id: 'month', label: 'Review month', helper: 'Month covered by the sanitation review.', type: 'date', placeholder: 'Select month' },
      { id: 'reviewer', label: 'Reviewer', helper: 'QA or sanitation manager leading the review.', type: 'person', placeholder: 'Select reviewer' },
      { id: 'monthly-summary', label: 'Monthly summary', helper: 'High-level performance and action summary.', type: 'textarea', placeholder: 'Summarise monthly sanitation performance' },
    ],
  },
  {
    key: 'cleaning-verification-annual',
    label: 'Cleaning Verification - Annual',
    shortLabel: 'Cleaning Annual',
    icon: 'badge-check',
    group: 'Cleaning Verification',
    frequency: 'ANNUAL',
    description: 'Review annual sanitation programme effectiveness, scope, training, and verification strategy for the coming year.',
    summary: 'Annual sanitation verification focused on programme design, controls, and future improvements.',
    statusLabel: 'Annual review',
    statusTone: 'emerald',
    completionExpectation: 'One annual programme evaluation and reset.',
    evidenceLabel: 'Reserve space for annual review packs, audit evidence, and signoff documents.',
    cleaningVerificationTemplate: cleaningVerificationTemplates.annual,
    checklist: [
      { id: 'clean-annual-scope', label: 'Programme scope reviewed', note: 'Confirm all lines, rooms, and support areas remain covered.' },
      { id: 'clean-annual-training', label: 'Training and competency reviewed', note: 'Assess training refresh needs for sanitation staff.' },
      { id: 'clean-annual-improvement', label: 'Improvement priorities defined', note: 'Set annual sanitation improvement or investment priorities.' },
    ],
    fields: [
      { id: 'review-year', label: 'Review year', helper: 'Year of the annual sanitation evaluation.', type: 'date', placeholder: 'Select year' },
      { id: 'annual-owner', label: 'Review owner', helper: 'Cross-functional owner of the annual review.', type: 'person', placeholder: 'Select owner' },
      { id: 'annual-summary', label: 'Annual summary', helper: 'Summarise the annual assessment and next-year priorities.', type: 'textarea', placeholder: 'Summarise annual cleaning verification outcomes' },
    ],
  },
  {
    key: 'ablution-facility-record',
    label: 'Ablution Facility Record',
    shortLabel: 'Ablution',
    icon: 'bath',
    group: 'Daily Records',
    frequency: 'DAILY',
    description: 'Track daily condition and serviceability of ablution facilities used by staff and visitors.',
    summary: 'Daily facility hygiene and serviceability record for toilets, handwash, and consumables.',
    statusLabel: 'Due today',
    statusTone: 'olive',
    completionExpectation: 'One check per day, with more entries later if the process expands.',
    evidenceLabel: 'Space for replenishment proof, escalation notes, and facility photos if needed.',
    ablutionFacilityTemplate,
    checklist: [
      { id: 'ablution-clean', label: 'Facilities visibly clean', note: 'Check floors, basins, cubicles, and waste bins.' },
      { id: 'ablution-supplies', label: 'Consumables available', note: 'Soap, sanitizer, tissue, and hand-drying supplies available.' },
      { id: 'ablution-functional', label: 'Fixtures functional', note: 'Doors, taps, drains, and lights in working condition.' },
    ],
    fields: [
      { id: 'checked-by', label: 'Checked by', helper: 'Person who performed the inspection.', type: 'person', placeholder: 'Select checker' },
      { id: 'inspection-date', label: 'Inspection date', helper: 'Date the record applies to.', type: 'date', placeholder: 'Select date' },
      { id: 'facility-notes', label: 'Facility notes', helper: 'Record defects or replenishment needs.', type: 'textarea', placeholder: 'Add facility notes' },
    ],
  },
  {
    key: 'hygiene-record',
    label: 'Hygiene Record',
    shortLabel: 'Hygiene',
    icon: 'handshake',
    group: 'Daily Records',
    frequency: 'DAILY',
    description: 'Capture daily hygiene verification around personnel readiness, PPE compliance, and entry controls.',
    summary: 'Daily hygiene record for people controls before and during operations.',
    statusLabel: 'Due today',
    statusTone: 'olive',
    completionExpectation: 'One operational hygiene record per day.',
    evidenceLabel: 'Capture retraining notes, deviation logs, and evidence placeholders for exceptions.',
    hygieneRecordTemplate,
    checklist: [
      { id: 'hygiene-ppe', label: 'PPE compliance verified', note: 'Hairnets, coats, gloves, and footwear compliant.' },
      { id: 'hygiene-entry', label: 'Entry controls followed', note: 'Handwashing, sanitizing, and access flow compliant.' },
      { id: 'hygiene-behaviour', label: 'Personnel hygiene behaviour acceptable', note: 'Observe eating, jewelry, illness reporting, and personal cleanliness controls.' },
    ],
    fields: [
      { id: 'hygiene-owner', label: 'Observed by', helper: 'Person responsible for the hygiene verification.', type: 'person', placeholder: 'Select observer' },
      { id: 'hygiene-shift', label: 'Shift', helper: 'Shift or team observed.', type: 'select', placeholder: 'Select shift' },
      { id: 'hygiene-comments', label: 'Comments', helper: 'Capture retraining needs or behaviour concerns.', type: 'textarea', placeholder: 'Add hygiene observations' },
    ],
  },
  {
    key: 'visitors-questionnaire',
    label: 'Visitors Questionnaire',
    shortLabel: 'Visitors',
    icon: 'users',
    group: 'When Required Records',
    frequency: 'WHEN_REQUIRED',
    description: 'Capture visitor screening, access purpose, compliance acknowledgements, and escort details when external visitors enter site.',
    summary: 'On-demand visitor health, travel, induction, and authorization declaration record.',
    statusLabel: 'Created on entry',
    statusTone: 'amber',
    completionExpectation: 'Complete only when a visitor requires site access.',
    evidenceLabel: 'Reserve space for declarations, movement restrictions, and signed acknowledgements.',
    visitorQuestionnaireTemplate,
    checklist: [
      { id: 'visitor-health', label: 'Health screening completed', note: 'Complete medical declaration and recent illness questions.' },
      { id: 'visitor-induction', label: 'Induction training acknowledged', note: 'Confirm hygiene and food safety entry rules were explained.' },
      { id: 'visitor-authorization', label: 'Facility access authorized', note: 'Final proceed / do not proceed decision captured on the form.' },
    ],
    fields: [
      { id: 'visitor-name', label: 'Visitor name', helper: 'Name of the visitor or contractor.', type: 'text', placeholder: 'Enter visitor name' },
      { id: 'host', label: 'Site contact', helper: 'Internal person responsible for the visitor.', type: 'person', placeholder: 'Select site contact' },
      { id: 'visit-date', label: 'Visit date', helper: 'Date of the visit.', type: 'date', placeholder: 'Select date' },
      { id: 'visitor-notes', label: 'Restrictions / notes', helper: 'Record declarations, movement restrictions, or follow-up actions.', type: 'textarea', placeholder: 'Add restrictions or notes' },
    ],
  },
]
